<?php

namespace Database\Seeders;
use App\Models\kartu_inv as ModelsKartuinv;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class kartuinvSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ModelsKartuinv::create([
            'id' => '1',
            'jenis_koleksi' => 'keris',
            'sub_koleksi' => 'keris jawa',
            'no_inv' => '12345',
            'no_reg' => '54321',
            'no_reg_foto' => '55555',
            'nama_kol' => '121212',
            'ur_bagian' => '-',
            'ur_bentuk' => '-',
            'ur_bahan' => '',
            'ur_teknik' => '-',
            'ur_warna' => '-',
            'ur_dekorasi' => '-',
            'ur_ornamen' => '-',
            'ur_tenda' => '-',
            'ur_asesori' => '-',
            'ur_fungsi' => '-',
            'ur_simbol' => '-',
            'ur_arti' => '-',
            'ur_gaya' => '-',
            'ur_kelengkapan' => '-',
            'ukuran' => '-',
            'tempat_asal_pembuatan' => '-',
            'tgl_pembuatan' => '-',
            'cara_perolehan' => '-',
            'tgl_masuk' => '-',
            'kondisi_benda' => '-',
            'tempat_penyimpanan' => '-',
            'dicatat_oleh' => '-',
            'tgl_pencatatan' => '-',
            'sumber_literatur' => '-',
            'sumber_narasumber' => '-',
            'ket_lain' => '-',
            'foto_inv' => '-',
        ]);

        ModelsKartuinv::create([
            'id' => '2',
            'jenis_koleksi' => 'keris',
            'sub_koleksi' => 'keris jawa',
            'no_inv' => '12345',
            'no_reg' => '54321',
            'no_reg_foto' => '55555',
            'nama_kol' => '121212',
            'ur_bagian' => '-',
            'ur_bentuk' => '-',
            'ur_bahan' => '',
            'ur_teknik' => '-',
            'ur_warna' => '-',
            'ur_dekorasi' => '-',
            'ur_ornamen' => '-',
            'ur_tenda' => '-',
            'ur_asesori' => '-',
            'ur_fungsi' => '-',
            'ur_simbol' => '-',
            'ur_arti' => '-',
            'ur_gaya' => '-',
            'ur_kelengkapan' => '-',
            'ukuran' => '-',
            'tempat_asal_pembuatan' => '-',
            'tgl_pembuatan' => '-',
            'cara_perolehan' => '-',
            'tgl_masuk' => '-',
            'kondisi_benda' => '-',
            'tempat_penyimpanan' => '-',
            'dicatat_oleh' => '-',
            'tgl_pencatatan' => '-',
            'sumber_literatur' => '-',
            'sumber_narasumber' => '-',
            'ket_lain' => '-',
            'foto_inv' => '-',
        ]);

        ModelsKartuinv::create([
            'id' => '3',
            'jenis_koleksi' => 'keris',
            'sub_koleksi' => 'keris jawa',
            'no_inv' => '12345',
            'no_reg' => '54321',
            'no_reg_foto' => '55555',
            'nama_kol' => '121212',
            'ur_bagian' => '-',
            'ur_bentuk' => '-',
            'ur_bahan' => '',
            'ur_teknik' => '-',
            'ur_warna' => '-',
            'ur_dekorasi' => '-',
            'ur_ornamen' => '-',
            'ur_tenda' => '-',
            'ur_asesori' => '-',
            'ur_fungsi' => '-',
            'ur_simbol' => '-',
            'ur_arti' => '-',
            'ur_gaya' => '-',
            'ur_kelengkapan' => '-',
            'ukuran' => '-',
            'tempat_asal_pembuatan' => '-',
            'tgl_pembuatan' => '-',
            'cara_perolehan' => '-',
            'tgl_masuk' => '-',
            'kondisi_benda' => '-',
            'tempat_penyimpanan' => '-',
            'dicatat_oleh' => '-',
            'tgl_pencatatan' => '-',
            'sumber_literatur' => '-',
            'sumber_narasumber' => '-',
            'ket_lain' => '-',
            'foto_inv' => '-',
        ]);

        ModelsKartuinv::create([
            'id' => '4',
            'jenis_koleksi' => 'keris',
            'sub_koleksi' => 'keris jawa',
            'no_inv' => '12345',
            'no_reg' => '54321',
            'no_reg_foto' => '55555',
            'nama_kol' => '121212',
            'ur_bagian' => '-',
            'ur_bentuk' => '-',
            'ur_bahan' => '',
            'ur_teknik' => '-',
            'ur_warna' => '-',
            'ur_dekorasi' => '-',
            'ur_ornamen' => '-',
            'ur_tenda' => '-',
            'ur_asesori' => '-',
            'ur_fungsi' => '-',
            'ur_simbol' => '-',
            'ur_arti' => '-',
            'ur_gaya' => '-',
            'ur_kelengkapan' => '-',
            'ukuran' => '-',
            'tempat_asal_pembuatan' => '-',
            'tgl_pembuatan' => '-',
            'cara_perolehan' => '-',
            'tgl_masuk' => '-',
            'kondisi_benda' => '-',
            'tempat_penyimpanan' => '-',
            'dicatat_oleh' => '-',
            'tgl_pencatatan' => '-',
            'sumber_literatur' => '-',
            'sumber_narasumber' => '-',
            'ket_lain' => '-',
            'foto_inv' => '-',
        ]);

        ModelsKartuinv::create([
            'id' => '5',
            'jenis_koleksi' => 'keris',
            'sub_koleksi' => 'keris jawa',
            'no_inv' => '12345',
            'no_reg' => '54321',
            'no_reg_foto' => '55555',
            'nama_kol' => '121212',
            'ur_bagian' => '-',
            'ur_bentuk' => '-',
            'ur_bahan' => '',
            'ur_teknik' => '-',
            'ur_warna' => '-',
            'ur_dekorasi' => '-',
            'ur_ornamen' => '-',
            'ur_tenda' => '-',
            'ur_asesori' => '-',
            'ur_fungsi' => '-',
            'ur_simbol' => '-',
            'ur_arti' => '-',
            'ur_gaya' => '-',
            'ur_kelengkapan' => '-',
            'ukuran' => '-',
            'tempat_asal_pembuatan' => '-',
            'tgl_pembuatan' => '-',
            'cara_perolehan' => '-',
            'tgl_masuk' => '-',
            'kondisi_benda' => '-',
            'tempat_penyimpanan' => '-',
            'dicatat_oleh' => '-',
            'tgl_pencatatan' => '-',
            'sumber_literatur' => '-',
            'sumber_narasumber' => '-',
            'ket_lain' => '-',
            'foto_inv' => '-',
        ]);
    }
}
